# This is a basic workflow to help you get started with Actions

name: NuGet Checker

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  NuGet_Checker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Make Change
        run: |
          touch empty.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
